/**
 * @author: Carlos Farias 
 * @version: 1.0
 * 
 * Wrapper class created to store shipping external service data fields.
 */

 public class ShippingOptionsWrapper {
    
    public String name;
    public Decimal rate;
    public String provider;
    public Decimal otherCost;
    public String serviceName;
    public String carrier;
    public String classOfService;
    public String referenceNumber;
    public Boolean isActive;
    
}